# [dein.toml]

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'januswel/filer.vim'

[[plugins]]
repo = 'ejholmes/vim-forcedotcom'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'shmup/vim-sql-syntax'

[[plugins]]
repo = 'stanangeloff/php.vim'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'vim-scripts/indentpython.vim'

[[plugins]]
repo = 'shougo/vimshell.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'ekalinin/dockerfile.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'zxqfl/tabnine-vim'
